services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=doc_store'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=sbonacho'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
